---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      kerberos-dependencies:
        - "cryptography"
        - "krb5"
        - "gssapi"
        - "pyspnego"
        - "requests-kerberos"
        
